BUILDING_NAMES: dict[str, str] = {
    "ARTS": "Arts Building",
    "B66": "B-66",
    "B67": "B-67",
    "BNSN": "Benson Building",
    "BRLW": "Barlow Building",
    "BRMB": "Brimhall Building",
    "CANC": "Cancer Research Center",
    "CB": "Crabtree Building",
    "CONF": "Conference Center",
    "CTB": "Clyde Building",
    "DIST": "Distance Education",
    "EB": "Engineering Building",
    "ELLB": "Ellsworth Building",
    "ESC": "Earth Science Building",
    "FSSS": "Family Sciences Building",
    "GLFG": "Golf Course",
    "HAWF": "Harman Building",
    "HBLL": "Harold B. Lee Library",
    "HC": "Heritage Halls Commons",
    "HCEB": "Hinckley Center",
    "HGB": "Harris Fine Arts Center",
    "HLRA": "Helaman Halls",
    "HOSP": "Hospital",
    "HRCB": "Harold R. Clark Building",
    "HRCN": "HRCN",
    "IPF": "Indoor Practice Facility",
    "JFSB": "Joseph F. Smith Building",
    "JKB": "Jesse Knight Building",
    "JRCB": "John R. Christiansen Building",
    "JSB": "Joseph Smith Building",
    "KMBL": "Kimball Tower",
    "LNDC": "LNDC",
    "LSB": "Life Sciences Building",
    "LSGH": "Life Sciences Greenhouse",
    "LVES": "LaVell Edwards Stadium",
    "MARB": "Maeser Building",
    "MB": "Museum of Art Basement",
    "MC": "Monte L. Bean Museum",
    "MCA": "MCA",
    "MCDB": "MCDB",
    "MCKB": "McKay Building",
    "MLBM": "MLBM",
    "MLRS": "MLRS",
    "MOA": "Museum of Art",
    "MSRB": "MSRB",
    "NICB": "Nicholes Building",
    "NUF": "NUF",
    "RB": "Richards Building",
    "RBF": "Richards Building Fieldhouse",
    "ROTC": "ROTC Building",
    "SAB": "Smoot Administration Building",
    "SFH": "SFH",
    "SFLD": "Soccer Field",
    "SLC": "Salt Lake Center",
    "SNLB": "Snell Building",
    "TCB": "Thomas L. Clyde Building",
    "TCF": "TCF",
    "TLRA": "Towers",
    "TLRB": "Towers B",
    "TMCB": "Talmage Building",
    "TNRB": "Tanner Building",
    "TRAK": "Track & Field",
    "TRPN": "TRPN",
    "TRPS": "TRPS",
    "UPC": "University Press / Creative Works",
    "WCAS": "WCAS",
    "WCCB": "WCCB",
    "WCCL": "WCCL",
    "WCOB": "Marriott School of Business",
    "WSC": "Wilkinson Student Center",
    "WVB": "Wymount Village",
}

ALL_BUILDINGS: list[str] = [
    "ARTS", "B66", "B67", "BNSN", "BRLW", "BRMB", "CANC", "CB", "CONF", "CTB",
    "DIST", "EB", "ELLB", "ESC", "FSSS", "GLFG", "HAWF", "HBLL", "HC", "HCEB",
    "HGB", "HLRA", "HOSP", "HRCB", "HRCN", "IPF", "JFSB", "JKB", "JRCB", "JSB",
    "KMBL", "LNDC", "LSB", "LSGH", "LVES", "MARB", "MB", "MC", "MCA", "MCDB",
    "MCKB", "MLBM", "MLRS", "MOA", "MSRB", "NICB", "NUF", "RB", "RBF", "ROTC",
    "SAB", "SFH", "SFLD", "SLC", "SNLB", "TCB", "TCF", "TLRA", "TLRB", "TMCB",
    "TNRB", "TRAK", "TRPN", "TRPS", "UPC", "WCAS", "WCCB", "WCCL", "WCOB", "WSC", "WVB",
]


def get_display_name(code: str) -> str:
    return BUILDING_NAMES.get(code, code)
